<?php
declare(strict_types=1);

use Dhl\Paket\Model\ShippingSettings\ShippingOption\Codes as DhlCodes;
use Hyva\ShippingDhlDe\ViewModel\Tooltip;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;

/** @var \Hyva\ShippingDhlDe\Magewire\DeliveryOptions $magewire */
$magewire = $block->getData('dhl_delivery_options');
if (!$magewire instanceof \Hyva\ShippingDhlDe\Magewire\DeliveryOptions) {
    return;
}
$viewModels = $block->getData('dhl_view_models') ?? ($viewModels ?? null);
if (!$viewModels instanceof \Hyva\Theme\Model\ViewModelRegistry) {
    return;
}
$escaper = $block->getData('dhl_escaper') ?? ($escaper ?? null);
if (!$escaper instanceof \Magento\Framework\Escaper) {
    return;
}
$tooltip = $viewModels->require(Tooltip::class);
$formatterViewModel = $viewModels->require(FormatterViewModel::class);
$code = DhlCodes::SERVICE_OPTION_GOGREEN_PLUS;
if ($magewire->isOptionHidden($code)) { return; }
$disabled = $magewire->isOptionDisabled($code);
$feenote = str_replace('$1', $formatterViewModel->currency($magewire->goGreenPlusFee), __('This service will incur additional shipping costs of $1 including VAT.')->render());
$feeNoteId = 'gogreen-plus-fee-note';
?>
<fieldset class="p-4 bg-white rounded-lg mt-0">
    <div class="flex items-start mb-2">
        <legend class="text-slate-800 text-base font-medium mb-0"><?= $escaper->escapeHtml(__('GoGreen Plus: Climate Neutral Shipping')) ?></legend>
        <?= /* @noEscape */ $tooltip->render(__('Climate-neutral shipping with DHL GoGreen Plus. Available for domestic German shipments only.')) ?>
    </div>
    <label class="inline-flex items-start gap-x-4" for="gogreen_plus_enabled">
        <input id="gogreen_plus_enabled" class="form-checkbox flex-none" type="checkbox" value="1" wire:click="toggleGoGreenPlus" <?= (bool)$magewire->goGreenPlusEnabled ? 'checked' : '' ?> <?= $disabled ? 'disabled' : '' ?> <?= $magewire->goGreenPlusFee > 0 ? 'aria-describedby="' . $escaper->escapeHtmlAttr($feeNoteId) . '"' : '' ?> />
        <span class="text-gray-700 hover:cursor-pointer"><?= $escaper->escapeHtml(__('Enable GoGreen Plus')) ?></span>
    </label>
    <?php if ($magewire->goGreenPlusFee > 0): ?><p class="text-sm" id="<?= $escaper->escapeHtmlAttr($feeNoteId) ?>"><?= $escaper->escapeHtml($feenote); ?></p><?php endif; ?>
</fieldset>
