<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\ShippingDhlDe\Magewire\GoGreenPlus;
use Hyva\ShippingDhlDe\ViewModel\Tooltip;
use Hyva\Checkout\ViewModel\Checkout\Formatter as FormatterViewModel;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var GoGreenPlus $magewire */
/** @var Tooltip $tooltip */
$tooltip = $viewModels->require(Tooltip::class);
/** @var FormatterViewModel $formatterViewModel */
$formatterViewModel = $viewModels->require(FormatterViewModel::class);

$feenote = __('This service will incur additional shipping costs of $1 including VAT.')->render();
$feenote = str_replace('$1', $formatterViewModel->currency($magewire->fee), $feenote);
$feeNoteId = 'gogreen-plus-fee-note'; // Eindeutige ID für die Verknüpfung
?>

<fieldset class="p-4 bg-white rounded-lg mt-0<?= $magewire->hidden ? ' hidden' : '' ?>">
    <div class="flex items-start mb-2">
        <legend class="text-slate-800 text-base font-medium mb-0">
            <?= $escaper->escapeHtml(__('GoGreen Plus: Climate Neutral Shipping')) ?>
        </legend>
        <?= /* @noEscape */ $tooltip->render(__('Climate-neutral shipping with DHL GoGreen Plus. Available for domestic German shipments only.')) ?>
    </div>

    <label class="inline-flex items-start gap-x-4"
           for="gogreen_plus_enabled">
        <input id="gogreen_plus_enabled"
               class="form-checkbox flex-none"
               type="checkbox"
               wire:click="toggleGoGreenPlus"
			   <?= (bool) $magewire->goGreenPlusEnabled ? 'checked' : '' ?>
               <?= $magewire->disabled ? 'disabled' : '' ?>
               <?php if ($magewire->fee > 0): ?>
                   aria-describedby="<?= $escaper->escapeHtmlAttr($feeNoteId) ?>"
               <?php endif; ?>
        />
        <span class="text-gray-700 hover:cursor-pointer">
            <?= $escaper->escapeHtml(__('Enable GoGreen Plus')) ?>
        </span>
    </label>
    
    <?php if ($magewire->fee > 0): ?>
        <p class="text-sm" id="<?= $escaper->escapeHtmlAttr($feeNoteId) ?>">
            <?= $escaper->escapeHtml($feenote); ?>
        </p>
    <?php endif; ?>
</fieldset>